name: Build and Release SafeNest APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Extract version from pubspec
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d '+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build APKs
        run: flutter build apk --release --split-per-abi

      - name: Rename APKs
        run: |
          VERSION=${{ steps.version.outputs.version }}

          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk safenest_${VERSION}_arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk safenest_${VERSION}_armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk safenest_${VERSION}_x86_64.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: SafeNest v${{ steps.version.outputs.version }}
          files: |
            safenest_*.apk
