name: Build and Release SafeNest APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install dependencies
        run: flutter pub get

      # 🔑 Recreate the keystore from GitHub secret
      - name: Decode Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks

      # 🔑 Create key.properties for Gradle signing
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Extract version from pubspec
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d '+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Signed APKs
        run: flutter build apk --release --split-per-abi

      - name: Rename APKs
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk safenest_${VERSION}_arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk safenest_${VERSION}_armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk safenest_${VERSION}_x86_64.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: SafeNest v${{ steps.version.outputs.version }}
          files: |
            safenest_*.apk